/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfazgrafica;

import javax.swing.JFrame;

/**
 *
 * @author jaime
 */
public class ResultadosObtenidos extends javax.swing.JFrame {

    public int C = 0; // Numero de conjuntos o sets
    public int W = 0; // Numero de palabras por bloque
    
    /**
     * Creates new form ResultadosObtenidos
     */
    public ResultadosObtenidos(int C, int W) {
        initComponents();
        CJTextField.setText(String.valueOf(C));
        WJTextField.setText(String.valueOf(W));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        titulojLabel = new javax.swing.JLabel();
        NumeroSetsJTextField = new javax.swing.JTextField();
        CJTextField = new javax.swing.JTextField();
        PalabrasBloquejTextField = new javax.swing.JTextField();
        WJTextField = new javax.swing.JTextField();
        VolverjButton = new javax.swing.JButton();
        TecnicasOptimizacionjButton = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulojLabel.setText("Mostrando los resultados obtenidos");

        NumeroSetsJTextField.setEditable(false);
        NumeroSetsJTextField.setText(" Numero de conjuntos o sets = ");
        NumeroSetsJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroSetsJTextFieldActionPerformed(evt);
            }
        });

        CJTextField.setEditable(false);
        CJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CJTextFieldActionPerformed(evt);
            }
        });

        PalabrasBloquejTextField.setEditable(false);
        PalabrasBloquejTextField.setText(" Numero de palabras por bloque = ");
        PalabrasBloquejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PalabrasBloquejTextFieldActionPerformed(evt);
            }
        });

        WJTextField.setEditable(false);

        VolverjButton.setText("Volver");
        VolverjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverjButtonActionPerformed(evt);
            }
        });

        TecnicasOptimizacionjButton.setText("Menu de tecnicas de optimizacion");
        TecnicasOptimizacionjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TecnicasOptimizacionjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(titulojLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NumeroSetsJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addGap(22, 22, 22)
                        .addComponent(CJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PalabrasBloquejTextField)
                            .addComponent(TecnicasOptimizacionjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VolverjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(WJTextField))))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titulojLabel)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumeroSetsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PalabrasBloquejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VolverjButton)
                    .addComponent(TecnicasOptimizacionjButton))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumeroSetsJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroSetsJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroSetsJTextFieldActionPerformed

    private void CJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CJTextFieldActionPerformed

    private void PalabrasBloquejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PalabrasBloquejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PalabrasBloquejTextFieldActionPerformed

    private void VolverjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverjButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ObtencionDatosMemoriaCache().setVisible(true);
    }//GEN-LAST:event_VolverjButtonActionPerformed

    private void TecnicasOptimizacionjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TecnicasOptimizacionjButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        JFrame ventana = new MenuTecnicasOptimizacion(C,W);
        ventana.setVisible(true);
    }//GEN-LAST:event_TecnicasOptimizacionjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultadosObtenidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultadosObtenidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultadosObtenidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultadosObtenidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private int C, W;
            public void run() {
                new ResultadosObtenidos(this.C,this.W).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CJTextField;
    private javax.swing.JTextField NumeroSetsJTextField;
    private javax.swing.JTextField PalabrasBloquejTextField;
    private javax.swing.JButton TecnicasOptimizacionjButton;
    private javax.swing.JButton VolverjButton;
    private javax.swing.JTextField WJTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel titulojLabel;
    // End of variables declaration//GEN-END:variables
}
