# Makefile de la practica 3 de tecnicas de optimizacion

all: original_O0 padded_O0 original_02 padded_O2

# Creamos el fichero ejecutable original_O0

original_O0: original.cpp
	g++ -o original_O0 original.cpp -O0

# Creamos el ejecutable padded

padded_O0: padded.cpp 
	g++ padded.cpp -o padded_O0

# Creamos el fichero ejecutable original_O2

original_02: original.cpp
	g++ original.cpp -o original_O2 -O2

# Creamos el ejecutable padded_O2

padded_O2: padded.cpp 
	g++ padded.cpp -o padded_O2 -O2


